# Generated by Django 4.2.7 on 2023-11-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flights",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flight_ID", models.IntegerField(max_length=4)),
                ("destination", models.CharField(max_length=3)),
                ("arrival", models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat_number", models.IntegerField(max_length=2)),
                ("user_ID", models.IntegerField(max_length=4)),
            ],
        ),
    ]
