# Generated by Django 4.2.7 on 2023-11-22 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin", models.CharField(max_length=3)),
                ("destination", models.CharField(max_length=3)),
                ("date", models.DateField()),
                ("departure_time", models.TimeField()),
                ("arrival_time", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Plane",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plane_model", models.CharField(max_length=50)),
                ("seating_capacity", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat_number", models.IntegerField()),
                ("seat_type", models.CharField(max_length=1)),
                ("availability", models.BooleanField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "flight_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.flight"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flight_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.flight"
                    ),
                ),
                (
                    "seat_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.seat"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Registered_Users",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.user",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=20)),
            ],
            bases=("app.user",),
        ),
        migrations.AddField(
            model_name="flight",
            name="plane_ID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.plane"
            ),
        ),
        migrations.CreateModel(
            name="Crew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                (
                    "flight_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.flight"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("insurance", models.BooleanField()),
                (
                    "flight_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.flight"
                    ),
                ),
                (
                    "user_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.user"
                    ),
                ),
            ],
        ),
    ]
